name: Build distribution zip

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build & zip
        run: npm run dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: s2j-alliance-manager-dist-zip
          path: release/*.zip
